name: screenshot_prevention
description: A Flutter plugin to prevent screenshots on specific screens.
version: 0.0.3
repository: https://github.com/innovationmauritiustelecom/screenshot_prevention

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.screenshot_prevention
        pluginClass: ScreenshotPreventionPlugin
      # ios:
      #   pluginClass: ScreenshotPreventionPlugin
